[build]
  publish = 'site/'
  command = 'yarn deploy'

[functions]
  directory = 'functions/'

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
